---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

tasks:
  flyway:install:
    desc: "Install flyway binary."
    cmds:
      - brew install flyway

  flyway:check-install:
    desc: "Checks if flyway binary present."
    cmds:
      - task: flyway:install
    status:
      - which flyway