---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json

version: "3"

tasks:
  local-db-build:
    desc: "Setup local DB."
    cmds:
      - docker-compose -f docker-compose.yml up -d db

  local-app-build:
    desc: "Build and run service inside docker."
    cmds:
      - docker-compose -f docker-compose.yml up -d app

  local-migration-build:
    desc: "Runs flyway migration."
    cmds:
      - docker-compose -f docker-compose.yml up -d flyway

  docker-compose-down:
    desc: "Execute docker-compose down command"
    cmds:
      - docker-compose down

  docker-compose-up:
    desc: "Execute docker-compose up command"
    cmds:
      - docker-compose up
